### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by IoTiFeelo** [IoTiFeelo/US-Monetary-Policy-GFC-Replication#6]
Goof afternoon @donotdespair,

I have completed my part 3 submission, but my RStudio doesn't render the project because my pc does not have enough application memory. I am drawing 20 thousand draws for the IRFs and that's causing problems to my laptop. 
The interesting thing is that the code runs smoothly by itself, but if I want to render the file I cannot. Should I reduce the number of draws? I bet Github should be able to update the website optimally (or maybe not?).

Thank you for your help,

Filippo

**Comment by donotdespair** [comment]
Hey @IoTiFeelo 

Yes, reducing the number of draws to `10000` is no problem for this report!

Greetings, T
